# -*- coding: utf-8 -*-
"""1text_sumirization tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALb8-FMmxU3PNLqJ-HJj3jwXeDJhgIoX

Your code implements a hybrid text summarization system that combines extractive summarization using Natural Language Processing (NLTK) and abstractive summarization using a deep learning transformer model (BART). First, the required libraries such as NLTK, PyTorch, and Transformers are imported, and the necessary NLTK resources like punkt and stopwords are downloaded to enable sentence and word tokenization. The program then checks whether a GPU is available using PyTorch and automatically selects GPU (if available) or CPU for running the model. Next, the BART-large-CNN pretrained transformer model is loaded using the HuggingFace pipeline for abstractive summarization. The extractive summarization function analyzes the text by splitting it into sentences, removing stop words, calculating word frequencies, and assigning scores to sentences based on the importance of words and sentence position. The top-ranked sentences are selected to form an extractive summary. The abstractive summarization function uses the BART model to generate a new concise summary that captures the meaning of the text rather than copying sentences directly. Finally, the program processes a sample article, prints the original text and word count, and outputs both the extractive summary and the abstractive summary, demonstrating how classical NLP techniques and deep learning models can be combined to produce efficient automatic text summaries.
"""

!pip uninstall -y transformers
!pip install transformers==4.41.2 sentencepiece accelerate

!pip install nltk transformers torch sentencepiece

"""1"""

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

import torch
print("GPU Available:", torch.cuda.is_available())
print("GPU Name:", torch.cuda.get_device_name(0))

!pip uninstall sentence-transformers -y

import re
import heapq
from collections import defaultdict
import nltk
import torch
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from transformers import pipeline

# Ensure the transformers library is up-to-date and correctly installed.
nltk.download('punkt')
nltk.download('stopwords')
# --------------------------------------------------
# DEVICE SETUP (Auto GPU if available)
# --------------------------------------------------

device = 0 if torch.cuda.is_available() else -1

print("GPU Available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))

# --------------------------------------------------
# LOAD TRANSFORMER MODEL (BART)
# --------------------------------------------------

summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn",
    device=device
)

# --------------------------------------------------
# EXTRACTIVE SUMMARIZATION
# --------------------------------------------------

def extractive_summarize(text, num_sentences=4):
    if not text.strip():
        return ""

    sentences = sent_tokenize(text)
    stop_words = set(stopwords.words("english"))
    freq = defaultdict(int)

    # Word frequency
    for word in word_tokenize(text.lower()):
        if word.isalnum() and word not in stop_words:
            freq[word] += 1

    if not freq:
        return " ".join(sentences[:num_sentences])

    max_freq = max(freq.values())

    # Score sentences
    scores = {}
    for i, sent in enumerate(sentences):
        words = word_tokenize(sent.lower())
        score = sum(freq[w] / max_freq for w in words if w in freq)

        # Position bonus
        position_bonus = max(0, 1.5 - i * 0.3)
        scores[sent] = score * (1 + position_bonus)

    # Select top sentences
    top_sentences = heapq.nlargest(num_sentences, scores, key=scores.get)
    top_sentences.sort(key=lambda s: sentences.index(s))

    return " ".join(top_sentences)

# --------------------------------------------------
# ABSTRACTIVE SUMMARIZATION
# --------------------------------------------------

def abstractive_summarize(text):
    summary = summarizer(
        text,
        max_length=130,
        min_length=40,
        do_sample=False
    )[0]["summary_text"]

    return summary.strip()

# --------------------------------------------------
# MAIN SUMMARIZATION FUNCTION
# --------------------------------------------------

def summarize_article(article):
    result = {}

    result["original_words"] = len(article.split())

    extractive = extractive_summarize(article)
    result["extractive"] = extractive

    abstractive = abstractive_summarize(article)
    result["abstractive"] = abstractive

    return result

# --------------------------------------------------
# DEMO ARTICLE (You Can Replace This)
# --------------------------------------------------

article = """
The Indian Premier League (IPL) 2026 season has begun with explosive performances across multiple venues.
Royal Challengers Bengaluru started their campaign with a thrilling victory over Chennai Super Kings.
Virat Kohli played a match-winning knock while bowlers dominated the death overs.
Several records have already been broken including the highest team total and fastest fifty.
Experts predict another high-scoring season due to batting-friendly pitches.
Franchises are focusing on aggressive middle-order strategies and improved death bowling.
Viewership is expected to cross 550 million globally.
"""

print("\n" + "="*80)
print("ORIGINAL ARTICLE:\n")
print(article)
print("\nWord Count:", len(article.split()))

print("\n" + "="*80)

summary = summarize_article(article)

print("\nEXTRACTIVE SUMMARY:\n")
print(summary["extractive"])

print("\n" + "="*80)

print("\nABSTRACTIVE SUMMARY:\n")
print(summary["abstractive"])

print("\n" + "="*80)



