# -*- coding: utf-8 -*-
"""2.Speech_recoginition_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nIWxh_kL2QRL-D24Bn_A-WR8A7i6H15l

The code performs speech-to-text transcription using Faster Whisper, an optimized implementation of OpenAI Whisper. It first imports the required libraries and defines a function that accepts an audio file path, model size, language option, and beam search size. When executed, the program loads the selected Whisper model (in this case large-v3) and automatically chooses GPU (CUDA) if available through PyTorch, otherwise it runs on the CPU. After the model is loaded, the audio file is processed and divided into small segments while applying voice activity detection (VAD) to remove silent portions. The model then analyzes each segment and converts the spoken audio into text using beam search decoding for better accuracy. It also detects the language of the speech automatically and prints the transcription along with the time stamps for each segment. Finally, all the recognized text segments are combined into a single full transcription and returned as the output.
"""

!pip install faster-whisper
# If you want GPU acceleration (faster on Colab's T4):
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

!pip install faster-whisper

from faster_whisper import WhisperModel
import time
import torch

def transcribe_with_faster_whisper(
    audio_path="/content/e5b01b48-8244-4727-a784-1886993c0df2 (online-audio-converter.com).mp3",
    model_size="medium",         # tiny / base / small / medium / large-v3
    language="None",               # None = auto-detect
    beam_size=5
):
    start = time.time()

    # Load model (downloads ~150 MB – 3 GB on first run)
    model = WhisperModel(
        model_size,
        device="cuda" if torch.cuda.is_available() else "cpu",  # or "cpu"
        compute_type="float16" if torch.cuda.is_available() else "int8",  # faster & lighter
    )

    print(f"Model loaded in {time.time()-start:.1f} s\n")

    segments, info = model.transcribe(
        audio_path,
        beam_size=beam_size,
        language=language,
        vad_filter=True,           # removes silence
    )

    print(f"Detected language: {info.language} (prob: {info.language_probability:.2f})")
    print(f"Transcription (took {time.time()-start:.1f} s total):\n")

    full_text = []
    for segment in segments:
        print(f"[{segment.start:.1f}s → {segment.end:.1f}s] {segment.text}")
        full_text.append(segment.text)

    return " ".join(full_text)


result = transcribe_with_faster_whisper("/content/e5b01b48-8244-4727-a784-1886993c0df2 (online-audio-converter.com).mp3", model_size="large-v3")



