# -*- coding: utf-8 -*-
"""3_Neural Style Transfer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VpTA56mPvv4R4zbhd0DyT4tiMa4-GDLb

This Python script implements neural style transfer using PyTorch, adapting the content and artistic style from two input images—a photograph (content) and an artwork (style)—to generate a stylized output while preserving the original composition. It begins by setting up the device (GPU if available) and image preprocessing transforms to resize and normalize images to tensors; utility functions load and display images via PIL and Matplotlib. A pretrained VGG19 feature extractor is loaded and frozen, with selected convolutional layers designated for content (e.g., 'conv_4') and style (e.g., 'conv_1' to 'conv_5') losses. Custom loss modules are defined: ContentLoss uses MSE to match deep features for structural fidelity; StyleLoss computes Gram matrices to capture texture correlations; and TotalVariationLoss penalizes pixel gradients for smoothness. The core get_style_model_and_losses function constructs a sequential model by interleaving VGG layers with these losses, precomputing targets from style and content inputs. Optimization then iteratively refines a cloned content image using L-BFGS, balancing weighted style, content, and TV losses over 400 steps, clamping values to [0,1] for validity, and logging progress every 50 iterations. Finally, it visualizes the originals and result via Matplotlib, saving the output as "stylized_output.jpg" for easy reuse in artistic image generation tasks.

# New section
"""

# Neural Style Transfer - FIXED VERSION
# Run in Google Colab with GPU: Runtime > Change runtime type > T4 GPU
# Upload content.jpg and style.jpg to /content/ before running

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import torchvision.models as models
from PIL import Image
import matplotlib.pyplot as plt
import copy

# ────────────────────────────────────────────────
#  Settings
# ────────────────────────────────────────────────

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Larger size = better quality (512 works well on T4 GPU)
imsize = 512 if torch.cuda.is_available() else 256

# ── FIX 1: Add ImageNet normalization (VGG19 REQUIRES this) ──
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

loader = transforms.Compose([
    transforms.Resize(imsize),
    transforms.CenterCrop(imsize),
    transforms.ToTensor(),
])

unloader = transforms.ToPILImage()

def image_loader(path):
    image = Image.open(path).convert('RGB')
    image = loader(image).unsqueeze(0)
    return image.to(device, torch.float)

def imshow(tensor, title=None, ax=None):
    image = tensor.cpu().clone().squeeze(0)
    image = unloader(image)
    if ax:
        ax.imshow(image)
        ax.axis('off')
        if title:
            ax.set_title(title)
    else:
        plt.imshow(image)
        if title:
            plt.title(title)
        plt.axis('off')
        plt.show()

# ────────────────────────────────────────────────
#  Load images
# ────────────────────────────────────────────────

content_path = "/content/sample_data/content.jpg"
style_path   = "/content/sample_data/style.jpg"

print(f"Loading: {content_path}")
print(f"Loading: {style_path}")

content_img = image_loader(content_path)
style_img   = image_loader(style_path)

print(f"Content image size: {content_img.shape}")
print(f"Style image size:   {style_img.shape}")

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
imshow(content_img, title='Content Image', ax=axes[0])
imshow(style_img,   title='Style Image',   ax=axes[1])
plt.tight_layout()
plt.show()

# ────────────────────────────────────────────────
#  FIX 2: Normalization layer for VGG19
# ────────────────────────────────────────────────

class Normalization(nn.Module):
    """Normalize input so VGG19 sees ImageNet-normalized values."""
    def __init__(self, mean, std):
        super().__init__()
        self.mean = torch.tensor(mean).to(device).view(-1, 1, 1)
        self.std  = torch.tensor(std).to(device).view(-1, 1, 1)

    def forward(self, img):
        return (img - self.mean) / self.std

# ────────────────────────────────────────────────
#  Loss modules
# ────────────────────────────────────────────────

class ContentLoss(nn.Module):
    def __init__(self, target):
        super().__init__()
        self.target = target.detach()
        self.loss = torch.tensor(0.0)

    def forward(self, x):
        self.loss = nn.functional.mse_loss(x, self.target)
        return x


def gram_matrix(x):
    a, b, c, d = x.size()
    features = x.view(a * b, c * d)
    G = torch.mm(features, features.t())
    return G.div(a * b * c * d)


class StyleLoss(nn.Module):
    def __init__(self, target_feature):
        super().__init__()
        self.target = gram_matrix(target_feature).detach()
        self.loss = torch.tensor(0.0)

    def forward(self, x):
        G = gram_matrix(x)
        self.loss = nn.functional.mse_loss(G, self.target)
        return x

# ────────────────────────────────────────────────
#  Build model
# ────────────────────────────────────────────────

# FIX 3: Use better layer choices
content_layers_default = ['conv_4']           # conv2_2 — preserves fine structure
style_layers_default   = ['conv_1', 'conv_2', 'conv_3', 'conv_4', 'conv_5']

def get_style_model_and_losses(cnn, norm_mean, norm_std,
                               style_img, content_img,
                               content_layers=content_layers_default,
                               style_layers=style_layers_default):

    normalization = Normalization(norm_mean, norm_std)
    model = nn.Sequential(normalization)

    content_losses = []
    style_losses   = []

    i = 0
    for layer in cnn.children():
        if isinstance(layer, nn.Conv2d):
            i += 1
            name = f'conv_{i}'
        elif isinstance(layer, nn.ReLU):
            name = f'relu_{i}'
            layer = nn.ReLU(inplace=False)
        elif isinstance(layer, nn.MaxPool2d):
            name = f'pool_{i}'
            # FIX 4: Average pooling gives smoother, better-looking results
            layer = nn.AvgPool2d(kernel_size=2, stride=2)
        elif isinstance(layer, nn.BatchNorm2d):
            name = f'bn_{i}'
        else:
            raise RuntimeError(f'Unrecognized layer: {layer.__class__.__name__}')

        model.add_module(name, layer)

        if name in content_layers:
            target = model(content_img).detach()
            cl = ContentLoss(target)
            model.add_module(f'content_loss_{i}', cl)
            content_losses.append(cl)

        if name in style_layers:
            target_feature = model(style_img).detach()
            sl = StyleLoss(target_feature)
            model.add_module(f'style_loss_{i}', sl)
            style_losses.append(sl)

    # Trim layers after last loss
    for j in range(len(model) - 1, -1, -1):
        if isinstance(model[j], (ContentLoss, StyleLoss)):
            break
    model = model[:(j + 1)]

    return model, style_losses, content_losses

# ────────────────────────────────────────────────
#  Load VGG19
# ────────────────────────────────────────────────

cnn = models.vgg19(weights='DEFAULT').features.to(device).eval()
for param in cnn.parameters():
    param.requires_grad = False

# ────────────────────────────────────────────────
#  Run style transfer
# ────────────────────────────────────────────────

model, style_losses, content_losses = get_style_model_and_losses(
    cnn, IMAGENET_MEAN, IMAGENET_STD, style_img, content_img
)

# Start from content image (better than noise for preserving structure)
input_img = content_img.clone().requires_grad_(True)

optimizer = optim.LBFGS([input_img], max_iter=20, line_search_fn='strong_wolfe')

# FIX 5: Balanced weights — style strong but not overwhelming
style_weight   = 1_000_000   # was 5_000_000 (way too high!)
content_weight = 1
tv_weight      = 1           # light smoothing

print("=" * 50)
print(f"Style weight:   {style_weight:,}")
print(f"Content weight: {content_weight}")
print(f"Steps:          300")
print("=" * 50)

run = [0]

def closure():
    with torch.no_grad():
        input_img.clamp_(0, 1)

    optimizer.zero_grad()
    model(input_img)

    style_score   = sum(sl.loss for sl in style_losses)   * style_weight
    content_score = sum(cl.loss for cl in content_losses) * content_weight

    # Simple TV loss for smoothness
    tv_loss = (
        torch.pow(input_img[:, :, 1:, :] - input_img[:, :, :-1, :], 2).mean() +
        torch.pow(input_img[:, :, :, 1:] - input_img[:, :, :, :-1], 2).mean()
    ) * tv_weight

    loss = style_score + content_score + tv_loss
    loss.backward()

    run[0] += 1
    if run[0] % 50 == 0:
        print(f"  Step {run[0]:3d} | "
              f"Style: {style_score.item():.1f} | "
              f"Content: {content_score.item():.1f} | "
              f"Total: {loss.item():.1f}")
    return loss

print("\nOptimizing...")
for _ in range(300):
    optimizer.step(closure)

with torch.no_grad():
    input_img.clamp_(0, 1)

# ────────────────────────────────────────────────
#  Show & save results
# ────────────────────────────────────────────────

fig, axes = plt.subplots(1, 3, figsize=(18, 6))
imshow(content_img, title='Content Image',   ax=axes[0])
imshow(style_img,   title='Style Image',     ax=axes[1])
imshow(input_img,   title='Stylized Result', ax=axes[2])
plt.tight_layout()
plt.show()

result = unloader(input_img.squeeze(0).cpu())
result.save("/content/stylized_output_fixed.jpg", quality=95)
print("\n✅ Saved as /content/stylized_output_fixed.jpg")

# ────────────────────────────────────────────────
#  BONUS: Try different style strengths
# ────────────────────────────────────────────────

print("\nTip: To tune the style strength, change style_weight:")
print("  • More painterly  → style_weight = 5_000_000")
print("  • Balanced        → style_weight = 1_000_000  (current)")
print("  • Subtle texture  → style_weight = 100_000")

# Neural Style Transfer - HIGH QUALITY VERSION v2
# Run in Google Colab with GPU: Runtime > Change runtime type > T4 GPU
# Upload content.jpg and style.jpg to /content/sample_data/ before running

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import torchvision.models as models
from PIL import Image, ImageFilter
import matplotlib.pyplot as plt
import copy
import numpy as np

# ────────────────────────────────────────────────
#  Settings
# ────────────────────────────────────────────────

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# UPGRADE 1: Higher resolution for GPU — 768 instead of 512
imsize = 768 if torch.cuda.is_available() else 256

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

def make_loader(size):
    return transforms.Compose([
        transforms.Resize(size),
        transforms.CenterCrop(size),
        transforms.ToTensor(),
    ])

unloader = transforms.ToPILImage()

def image_loader(path, size):
    image = Image.open(path).convert('RGB')
    image = make_loader(size)(image).unsqueeze(0)
    return image.to(device, torch.float)

def tensor_to_pil(tensor):
    return unloader(tensor.cpu().clone().squeeze(0).clamp(0, 1))

def imshow(tensor, title=None, ax=None):
    image = tensor_to_pil(tensor)
    if ax is not None:
        ax.imshow(image)
        ax.axis('off')
        if title:
            ax.set_title(title, fontsize=13, fontweight='bold')
    else:
        plt.imshow(image)
        if title:
            plt.title(title)
        plt.axis('off')
        plt.show()

# ────────────────────────────────────────────────
#  Load images
# ────────────────────────────────────────────────

content_path = "/content/sample_data/content.jpg"
style_path   = "/content/sample_data/style.jpg"

print(f"Loading images at {imsize}px...")
content_img = image_loader(content_path, imsize)
style_img   = image_loader(style_path,   imsize)

print(f"Content: {content_img.shape}  |  Style: {style_img.shape}")

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
imshow(content_img, title='Content Image', ax=axes[0])
imshow(style_img,   title='Style Image',   ax=axes[1])
plt.suptitle('Input Images', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()

# ────────────────────────────────────────────────
#  Normalization
# ────────────────────────────────────────────────

class Normalization(nn.Module):
    def __init__(self, mean, std):
        super().__init__()
        self.mean = torch.tensor(mean).to(device).view(-1, 1, 1)
        self.std  = torch.tensor(std).to(device).view(-1, 1, 1)
    def forward(self, img):
        return (img - self.mean) / self.std

# ────────────────────────────────────────────────
#  Loss modules
# ────────────────────────────────────────────────

class ContentLoss(nn.Module):
    def __init__(self, target):
        super().__init__()
        self.target = target.detach()
        self.loss = torch.tensor(0.0)
    def forward(self, x):
        self.loss = nn.functional.mse_loss(x, self.target)
        return x

def gram_matrix(x):
    a, b, c, d = x.size()
    features = x.view(a * b, c * d)
    G = torch.mm(features, features.t())
    return G.div(a * b * c * d)

class StyleLoss(nn.Module):
    def __init__(self, target_feature):
        super().__init__()
        self.target = gram_matrix(target_feature).detach()
        self.loss = torch.tensor(0.0)
    def forward(self, x):
        self.loss = nn.functional.mse_loss(gram_matrix(x), self.target)
        return x

# ────────────────────────────────────────────────
#  UPGRADE 2: Deeper content layer + more style layers
#  Using conv_8 (relu3_2) for content — captures richer structure
#  Style layers span all 5 VGG blocks for full texture capture
# ────────────────────────────────────────────────

content_layers = ['conv_8']                                        # relu3_2
style_layers   = ['conv_1', 'conv_3', 'conv_5', 'conv_9', 'conv_13']  # 1 per block

def build_model(cnn, norm_mean, norm_std, style_img, content_img):
    model = nn.Sequential(Normalization(norm_mean, norm_std))
    content_losses, style_losses = [], []
    i = 0

    for layer in cnn.children():
        if isinstance(layer, nn.Conv2d):
            i += 1; name = f'conv_{i}'
        elif isinstance(layer, nn.ReLU):
            name = f'relu_{i}'
            layer = nn.ReLU(inplace=False)
        elif isinstance(layer, nn.MaxPool2d):
            name = f'pool_{i}'
            layer = nn.AvgPool2d(2, stride=2)   # smoother gradients
        elif isinstance(layer, nn.BatchNorm2d):
            name = f'bn_{i}'
        else:
            raise RuntimeError(f'Unknown layer: {layer.__class__.__name__}')

        model.add_module(name, layer)

        if name in content_layers:
            cl = ContentLoss(model(content_img).detach())
            model.add_module(f'content_loss_{i}', cl)
            content_losses.append(cl)

        if name in style_layers:
            sl = StyleLoss(model(style_img).detach())
            model.add_module(f'style_loss_{i}', sl)
            style_losses.append(sl)

    # Trim after last loss
    for j in range(len(model)-1, -1, -1):
        if isinstance(model[j], (ContentLoss, StyleLoss)):
            break
    return model[:(j+1)], style_losses, content_losses

# ────────────────────────────────────────────────
#  Load VGG19
# ────────────────────────────────────────────────

cnn = models.vgg19(weights='DEFAULT').features.to(device).eval()
for p in cnn.parameters():
    p.requires_grad = False

# ────────────────────────────────────────────────
#  UPGRADE 3: Multi-scale style transfer
#  Start at low res, upscale, refine — faster & sharper results
# ────────────────────────────────────────────────

def run_style_transfer(content_img, style_img, n_steps=400,
                       style_weight=800_000, content_weight=1, tv_weight=0.5):

    model, style_losses, content_losses = build_model(
        cnn, IMAGENET_MEAN, IMAGENET_STD, style_img, content_img
    )

    input_img = content_img.clone().requires_grad_(True)
    optimizer = optim.LBFGS([input_img], max_iter=20, line_search_fn='strong_wolfe')

    run = [0]
    best = [None, float('inf')]

    def closure():
        with torch.no_grad():
            input_img.clamp_(0, 1)
        optimizer.zero_grad()
        model(input_img)

        style_score   = sum(sl.loss for sl in style_losses)   * style_weight
        content_score = sum(cl.loss for cl in content_losses) * content_weight
        tv_loss = (
            torch.pow(input_img[:,:,1:,:] - input_img[:,:,:-1,:], 2).mean() +
            torch.pow(input_img[:,:,:,1:] - input_img[:,:,:,:-1], 2).mean()
        ) * tv_weight

        loss = style_score + content_score + tv_loss
        loss.backward()

        run[0] += 1
        if run[0] % 50 == 0:
            print(f"  Step {run[0]:3d} | Style: {style_score.item():.2f} | "
                  f"Content: {content_score.item():.2f} | TV: {tv_loss.item():.4f}")

        if loss.item() < best[1]:
            best[1] = loss.item()
            best[0] = input_img.data.clone()

        return loss

    for _ in range(n_steps):
        optimizer.step(closure)

    with torch.no_grad():
        input_img.clamp_(0, 1)

    return best[0]

# ── Stage 1: Low resolution warmup (fast) ──
LOW_RES = 256
print("\n" + "="*55)
print(f"STAGE 1: Warmup at {LOW_RES}px (fast, ~1 min on GPU)")
print("="*55)

c_low = image_loader(content_path, LOW_RES)
s_low = image_loader(style_path,   LOW_RES)
result_low = run_style_transfer(c_low, s_low, n_steps=200,
                                style_weight=800_000, content_weight=1, tv_weight=0.5)

# ── Upscale warmup result to full resolution ──
print(f"\nUpscaling to {imsize}px for refinement pass...")
pil_low = tensor_to_pil(result_low)
pil_up  = pil_low.resize((imsize, imsize), Image.LANCZOS)
up_tensor = make_loader(imsize)(pil_up).unsqueeze(0).to(device, torch.float)

# ── Stage 2: Full resolution refinement ──
print("\n" + "="*55)
print(f"STAGE 2: Refinement at {imsize}px (higher quality)")
print("="*55)

result_final = run_style_transfer(content_img, style_img,
                                  n_steps=300,
                                  style_weight=600_000,
                                  content_weight=1,
                                  tv_weight=0.3)

# Override input init with upscaled result for even better quality
# (run a short polish pass starting from the upscaled warmup)
print("\n" + "="*55)
print("STAGE 3: Polish pass (starting from upscaled warmup)")
print("="*55)

model_f, sl_f, cl_f = build_model(cnn, IMAGENET_MEAN, IMAGENET_STD, style_img, content_img)
polish_img = up_tensor.clone().requires_grad_(True)
opt_p = optim.LBFGS([polish_img], max_iter=20, line_search_fn='strong_wolfe')
run2 = [0]

def closure2():
    with torch.no_grad():
        polish_img.clamp_(0, 1)
    opt_p.zero_grad()
    model_f(polish_img)
    style_score   = sum(sl.loss for sl in sl_f) * 600_000
    content_score = sum(cl.loss for cl in cl_f) * 1
    tv_loss = (
        torch.pow(polish_img[:,:,1:,:] - polish_img[:,:,:-1,:], 2).mean() +
        torch.pow(polish_img[:,:,:,1:] - polish_img[:,:,:,:-1], 2).mean()
    ) * 0.3
    loss = style_score + content_score + tv_loss
    loss.backward()
    run2[0] += 1
    if run2[0] % 50 == 0:
        print(f"  Polish {run2[0]:3d} | Total: {loss.item():.2f}")
    return loss

for _ in range(150):
    opt_p.step(closure2)

with torch.no_grad():
    polish_img.clamp_(0, 1)

# ────────────────────────────────────────────────
#  Show final comparison
# ────────────────────────────────────────────────

fig, axes = plt.subplots(1, 3, figsize=(20, 7))
imshow(content_img, title='📷 Content Image',       ax=axes[0])
imshow(style_img,   title='🎨 Style Image',          ax=axes[1])
imshow(polish_img,  title='✨ Stylized Result (v2)', ax=axes[2])
plt.suptitle('Neural Style Transfer — High Quality Result', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

# Also compare both passes
fig2, axes2 = plt.subplots(1, 2, figsize=(14, 6))
imshow(result_final, title='Single-pass result', ax=axes2[0])
imshow(polish_img,   title='Multi-scale result (better)', ax=axes2[1])
plt.suptitle('Single-pass vs Multi-scale Comparison', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# ────────────────────────────────────────────────
#  Save outputs
# ────────────────────────────────────────────────

tensor_to_pil(result_final).save("/content/stylized_singlepass.jpg",  quality=95)
tensor_to_pil(polish_img  ).save("/content/stylized_multiscale.jpg",  quality=95)
print("\n✅ Saved:")
print("   /content/stylized_singlepass.jpg  — single-pass result")
print("   /content/stylized_multiscale.jpg  — multi-scale (best quality)")

print("""
╔══════════════════════════════════════════════════════╗
║  TUNING GUIDE                                        ║
║                                                      ║
║  Too much style / loses content shape?               ║
║    → Lower style_weight to 300_000                   ║
║                                                      ║
║  Too subtle / not painterly enough?                  ║
║    → Raise style_weight to 1_500_000                 ║
║                                                      ║
║  Output looks blurry?                                ║
║    → Lower tv_weight to 0.1                          ║
║                                                      ║
║  Want even more detail?                              ║
║    → Set imsize = 1024 (needs >8GB VRAM)             ║
╚══════════════════════════════════════════════════════╝
""")